### ISSUE TITLE
FEATURE Request - Preheat screen updates

### ISSUE THREAD

**Issue by skylineboy200000** [klack/marlin#10]
### Requirements
In the Preheat screen display the preheat values associated with the materials displayed. I.e PLA 50/200, PETG 60/220, also allow these to be customised

Additionally allow a custom temperature option, where the value is saved to memory.

### Description
It would be useful to include the pre-set temperature values for the displayed filament options. I.e PLA 50/200 , PETG 60/225.

Additionally an option to pre-heat to a custom value.

### Benefits
User know what the target temperature will be.

**Comment by klack** [comment]
Moved to reddit
