### ISSUE TITLE
Feature request: turn on firmware retractions

### ISSUE THREAD

**Issue by Buriaku** [klack/marlin#100]
Firmware retractions aren't activated in the source code at the moment.

They shouldn't interfere with anything unless G10, G11 or M209 is called.

This allows more scripts to be executed e.g. at layer change.
Some post-processing scripts require it e.g. the toolchange post-processing script for PrusaSlicer implementing Cura-style prime towers:
https://github.com/mkudzia84/toolchanger-pspp

**Comment by klack** [comment]
Need to research the ramifications of turning this on, with regard to toolchanges, prusa slicer tool retraction (10mm default), and if it could affect filament change on screen or gcode.
 
![image](https://user-images.githubusercontent.com/4606571/114471585-1d1d3400-9bae-11eb-89b8-49289d0fccde.png)

**Comment by Buriaku** [comment]
You're totally right. Hadn't thought about tool changes. You could set all default lengths to zero, I guess.

**Comment by klack** [comment]
Moved to reddit
