### ISSUE TITLE
G29 P1 on machines with optical Y endstops only reaches 7x8 points

### ISSUE THREAD

**Issue by Buriaku** [klack/marlin#110]
Description:
As machines with optical Y endstops have Y7 as their home position, the 10x10 grid that is used for G29 has other values for the y rows than machines with mechanical Y endstops. This means that the 9th row is at Y275, which means that only probes with a offset closer than Y-45 can reach it. The standard mounts have a greater offset than that.
It would be nice if the grid could be determined dynamically based on the y offset of the probe or set such that probes with a slightly greater y offset can reach the 9th row.
An option for a build with a bigger grid could help also, but more rows may fall in the unreachable zone on both types of machines. The ideal solution would be to always put one of the rows at the maximum reachable y coordinate.

Expected behavior:
At least 8x8 grid points should be reachable with reasonable probe y offset.

Firmware flavor:
TMC2209_OpticalY_BLTouch

**Comment by klack** [comment]
Please test in latest version that addresses Y offsets.  Re open if needed
