### ISSUE TITLE
Filament runout doesn't work

### ISSUE THREAD

**Issue by galaxyman7** [klack/marlin#132]
**Describe the bug**
When the filament runs out, the touchscreen shows "finishing up" and freezes.

**Expected behavior**
Should give you the option to change filament

**Additional context**
Running luxuri firmware on a Hands 2. I installed the same touchscreen as the TL-D3. Using 2 A49 stepper drivers for the extruders, and 2208s for the rest. 
This was on a two color print. Not sure if it still happens with 1 material prints or not.

**Comment by klack** [comment]
Filament change not yet implemented.  It is disabled by default.
