### ISSUE TITLE
Z-Axis Stepper goes off by clicking pause

### ISSUE THREAD

**Issue by heyer4** [klack/marlin#143]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

After clicking on pause button, the Stepper in z-axis goes off and and the nozzle is crashing into the part. Then the Extruder is moving in x-direction while nozzle is scratching on the build plate. Please see in attached vide

https://user-images.githubusercontent.com/99029356/158700157-e426072b-cc52-4e13-ba7b-63eb0eb6ebcd.mp4

o

### Bug Timeline

Currently I haven't seen this bug.

### Expected behavior

Extruder should move a bit up and z-axis should stay on

### Actual behavior

z-axis goes off and crashes into part

### Steps to Reproduce

1. start a build job
2. click on pause

### Version of Marlin Firmware

2.0.9.2_20220207_2107 DP3_A4988

### Printer model

Tenlog TL 3D Pro

### Your Slicer

Cura

### Host Software

Pronterface

**Comment by klack** [comment]
Tested tenlog sample file.  Pausing is working as before.  In normal mode, extruders will goto their parked position.  In clone mode extruders stay and the bed slides forward.  I'm thinking this could be hardware related.
