### ISSUE TITLE
[BUG] (bug summary) Off brand bltouch does not work

### ISSUE THREAD

**Issue by enishi1357** [klack/marlin#148]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I made the clone bltouch work before on a skr mini e3 v3 board by commenting bltouch force sw, 5v, mode set lines and clone bltouch works. But on this machine it doesn't work.

### Expected behavior

The bltouch tip should go down when homing on the z axis.

### Actual behavior

The bltouch tip did not go down when homing on the z axis and octoprint error out and disconnect.

### Version of Marlin Firmware

D3P_2209_Titan_BLTouch

### Printer model

 TL-D3 Pro BMG Extruder model

### Bed Leveling

ABL Bilinear mesh

### Host Software

OctoPrint

**Comment by klack** [comment]
This needs to be a feature request.  We do not currently support off brand sensors.
