### ISSUE TITLE
[BUG] (bug summary) G29 not working. G28 does work.

### ISSUE THREAD

**Issue by enishi1357** [klack/marlin#149]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Entered g29 into terminal and nothing happen

### Version of Marlin Firmware

D3P_2209_Titan_BLTouch

### Printer model

 TL-D3 Pro

### Host Software

OctoPrint

**Comment by klack** [comment]
Make sure you are using the 2.0.9.2

Also feel free to join us in Discord for fast help!
https://discord.gg/gZpQbBTA
