### ISSUE TITLE
ISSUE: Screen not monitoring temperature changes set by Gcode

### ISSUE THREAD

**Issue by mine2209** [klack/marlin#17]
### Description
Screen is not displaying temperature changes occuring when intiated via gcode sender 

### Steps to Reproduce

1. Power up and connect via gcode sender (pronterface )
2. Send M104 T1 E200

**Expected behavior:**
Screen to register change and adjust target temp and show extruder temp increasing to target temp

**Actual behavior:** 
Screen registers no change to target temp or to current extruder temp, extruder does heat up.

#### Additional Information

The screen stops registering any temperature information once connected to via USB, if you manually adjust the temp on the screen it registers the current temp value at that moment and displays it and it changes the target temp but does not give real time temperature readings still.

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by klack** [comment]
Need to re verify this

**Comment by klack** [comment]
Fixed in 0.9.2 
This was due to external reset by plugging in usb
