### ISSUE TITLE
Feature Request: LCD UI: Pause or Cancel Print from OctoPrint via M118 Action gCode 

### ISSUE THREAD

**Issue by andrewseago** [klack/marlin#23]
https://marlinfw.org/docs/gcode/M118.html?fbclid=IwAR193RURHwHQuIRJrMS73JSAwPgohREv9IDe0k37HIeY1cGCqqZOmD0rX7E

Implement buttons in LDC UI for Pausing or Canceling a print from OctoPrint

**Comment by klack** [comment]
Moved to reddit
