### ISSUE TITLE
ISSUE: Printing clone mode from Octo

### ISSUE THREAD

**Issue by mine2209** [klack/marlin#33]
### Description

Causes E1 to attempt to move left from home position and skip

### Steps to Reproduce

1. Turn Idex mode to clone
2. Preheat
3. Send file to print from octoprint

**Expected behavior:**
Once preheated E2 to move to the centre position and then both nozzles to begin print

**Actual behavior:** 
Both E1 & E2 attempt to move left to the centre position causing E1 to push against endstop/frame then the print begins and completes normally

#### Additional Information

When printing from SD this does not happen E2 moves over E1 remains still and then it begins printing normally

https://user-images.githubusercontent.com/67610139/104075088-b92f4c00-5209-11eb-909a-ec15223a84c2.mp4

**Comment by murdock62** [comment]
Fixed by the fix of issue #104.
