### ISSUE TITLE
ISSUE: Clone mode nozzle hits bed clips

### ISSUE THREAD

**Issue by mine2209** [klack/marlin#36]
### Description

When printing in clone mode from GUI off SD the Nozzle does not Z lift to clear the stock bed clips holding down the glass bed

### Steps to Reproduce

1. Select clone mode
2. Print from SD

**Expected behavior:** 

E2 to Z lift and move to start position at centre location missing the clips on the bed

**Actual behavior:** 

E2 moves across THEN Z lifts so it just clips the handles of the clip and drags it along the glass on the way and then lifts

#### Additional Information

Can just remove handles for the mean time until this is fixed

**Comment by klack** [comment]
Fixed, ty @murdock62!
