### ISSUE TITLE
ISSUE: When swaping exruders in Auto mode E2 moving to "home" position causes bed to crash into Y endstop

### ISSUE THREAD

**Issue by mine2209** [klack/marlin#39]
### Description
When swaping exruders in Auto mode from E1 to E2 as E2 moves across to left corner position the bed is moved to the rear causing it to crash into the endstop and the motor skip

### Steps to Reproduce

1. Home bed
2. Select Swap tool
3. Swap to E2 "yes"

**Expected behavior:** 

E2 to move across to the left corner without crashing the bed 

**Actual behavior:** 
As E2 moves across the bed moves to the rear, causing it to crash 

#### Additional Information

Not sure but maybe to do with "trying to reach home position of Y0 and Y2 offset?

**Comment by murdock62** [comment]
Is can be corrected by the fix of issue # 76. (To test)

**Comment by klack** [comment]
Fixed by in latest release, bed size and Y min are now properly defined
