### ISSUE TITLE
Excessive character Length of gcode file results in the file not appearing on the SD card. 

### ISSUE THREAD

**Issue by skylineboy200000** [klack/marlin#5]
### Description

x/y values below need to be determined, I've not had the opportunity to go back and forth and work out the specific character length limits let. 

- File names <x length display in the "Print" GUI option when loading with SD Card

- File lengths between >x but <y still display in the "Print" GUI option when loading with SD Card BUT don't show the full file name
- File lengths >x do not display in the GUI at all (missing). 

### Steps to Reproduce

1. Set gcode file name to x length
2. Insert SD card into slot
3. Click "print" on GUI homescreen 
4. View files as explained in the description above

**Expected behavior:** [What you expect to happen]

Display all files regardless of the length
Extend GUI boundary box to allow visibility of larger file names
Support scrolling banner of file names for lengths that will not fit on screen.

**Actual behavior:** [What actually happens]

Shortened filename or file missing.

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by klack** [comment]
Marlin limitation, can be changed to a feature request if wanted.
