### ISSUE TITLE
Issue: Preheat button on occasion heats only bed

### ISSUE THREAD

**Issue by mine2209** [klack/marlin#50]
### Description

Preheat button does not set the extruder preheating only the bed

### Steps to Reproduce
No solid method but appears have only happened after print completed or cancelled

**Expected behavior:** 
Single press of preheat button to start preheating both extruder and bed to desired temp

**Actual behavior:**
Bed starts to preheat but extruder does not

#### Additional Information

Occured 3 times, I believe only after print has already been completed or has been cancelled?

The text highlights to show it has acknowledged the selection.

You can exit the menu and see the bed has been set to preheat but the extruder has not.

I have waited as Richard advised (in menu) and the issue did not resolve.

Upon pressing the screen to select either the same option again or a different the extruder begins to preheat as expected.

I have only had this happen for E1 and not E2 but I more often select E1 than E2

**Comment by klack** [comment]
Potentially fixed in 0.9.2
First command was being thrown out on screen wake
