### ISSUE TITLE
ISSUE: Crashing while homing after cancelling print

### ISSUE THREAD

**Issue by mine2209** [klack/marlin#76]
### Description

Crashing extruder on X while homing after cancelling print

### Steps to Reproduce

1. Print from octoprint cancel print
2. Move extruder out of way or into different position
3. Select home via UI or octo

**Expected behavior:** 

Home

**Actual behavior:** 

It attempts to move the extruders to park positions? from postion they were in before steppers disabled. resulting in crash it then homes

#### Additional Information

May also happen after allowing print to complete if you move extruders on X,

May also happen on Y will check and report

I believe was happening on last buld too

**Comment by murdock62** [comment]
Temporary fix.

**Comment by murdock62** [comment]
Seem to be fixed by modifying the g28.cpp file like this:

**Before :**

#if ENABLED(DUAL_X_CARRIAGE) // Used in tenlog config
   tool_change(0, false); 
#else // Used in tenlog config
   tool_change(0, true);
#endif // Used in tenlog config

**After :**
tool_change(0, true);
